### ISSUE TITLE
Won't render

### ISSUE THREAD

**Issue by Samriddha14** [YamaR1n/YamaRin-s-Legacy#4]
Till yesterday the shader was working fine. Today when I tried to play only the text in loading page and white colour of cloud(not in realistic way. Blocky cloud but white) were working.  I tried to deactivate and reactivate. Delete and reinstall.  Restart my laptop. But didn't start. My game version in  1.17

**Comment by YamaR1n** [comment]
Your game version must was 1.16.100 or earlier yesterday.  This shader is not working on 1.16.200 or later versions of windows 10 edition.

**Comment by creativegamer03** [comment]
the shader CAN still work with the 32bit version of bedrock (even with latest version, 1.18.10) since it DOESN'T have the RenderDragon engine, which is only available on the 64bit version of bedrock.
